name: 'OpenAPI Spec Diff'
description: 'A diff tool for OpenAPI Specification 3'
inputs:
  base:
    description: 'path of OpenAPI spec in YAML or JSON format'
    required: true
  revision:
    description: 'path of OpenAPI spec in YAML or JSON format'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base }}
    - ${{ inputs.revision }}
