name: 'OpenAPI Spec Diff'
description: 'A diff tool for OpenAPI Specification 3'
inputs:
  spec-path:
    description: 'path of OpenAPI spec in YAML or JSON format'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.spec-path }}