#!/bin/sh -l

# PATH=$1
# PR_BASE_REF=$GITHUB_BASE_REF
# PUSH_BASE_REF=$GITHUB_REF_NAME
# SHA=$GITHUB_SHA
# PREV_SHA=$GITHUB_ENV

# echo $PR_BASE_REF
# echo $PR_BASE_SHA
# echo $PUSH_BASE_REF
# echo $PREV_SHA


echo HOME=$HOME
echo GITHUB_JOB=$GITHUB_JOB 
echo GITHUB_REF=$GITHUB_REF
echo GITHUB_SHA=$GITHUB_SHA
echo GITHUB_REPOSITORY=$GITHUB_REPOSITORY
echo GITHUB_REPOSITORY_OWNER=$GITHUB_REPOSITORY_OWNER
echo GITHUB_RUN_ID=$GITHUB_RUN_ID
echo GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER
echo GITHUB_RETENTION_DAYS=$GITHUB_RETENTION_DAYS
echo GITHUB_RUN_ATTEMPT=$GITHUB_RUN_ATTEMPT
echo GITHUB_ACTOR=$GITHUB_ACTOR
echo GITHUB_WORKFLOW=$GITHUB_WORKFLOW
echo GITHUB_HEAD_REF=$GITHUB_HEAD_REF
echo GITHUB_BASE_REF=$GITHUB_BASE_REF
echo GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME
echo GITHUB_SERVER_URL=$GITHUB_SERVER_URL
echo GITHUB_API_URL=$GITHUB_API_URL
echo GITHUB_GRAPHQL_URL=$GITHUB_GRAPHQL_URL
echo GITHUB_REF_NAME=$GITHUB_REF_NAME
echo GITHUB_REF_PROTECTED=$GITHUB_REF_PROTECTED
echo GITHUB_REF_TYPE=$GITHUB_REF_TYPE
echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE
echo GITHUB_ACTION=$GITHUB_ACTION
echo GITHUB_EVENT_PATH=$GITHUB_EVENT_PATH
echo GITHUB_ACTION_REPOSITORY=$GITHUB_ACTION_REPOSITORY
echo GITHUB_ACTION_REF=$GITHUB_ACTION_REF
echo GITHUB_PATH=$GITHUB_PATH
echo GITHUB_ENV=$GITHUB_ENV
echo GITHUB_STEP_SUMMARY=$GITHUB_STEP_SUMMARY
echo RUNNER_OS=$RUNNER_OS
echo RUNNER_ARCH=$RUNNER_ARCH
echo RUNNER_NAME=$RUNNER_NAME
echo RUNNER_TOOL_CACHE=$RUNNER_TOOL_CACHE
echo RUNNER_TEMP=$RUNNER_TEMP
echo RUNNER_WORKSPACE=$RUNNER_WORKSPACE
echo ACTIONS_RUNTIME_URL=$ACTIONS_RUNTIME_URL
echo ACTIONS_RUNTIME_TOKEN=$ACTIONS_RUNTIME_TOKEN
echo ACTIONS_CACHE_URL=$ACTIONS_CACHE_URL
echo GITHUB_ACTIONS=$GITHUB_ACTIONS
echo CI=$CI
# echo "Retrieving changes between $PREV_SHA ($PREV_BRANCH) → $CURRENT_SHA ($CURRENT_BRANCH)"

# cp /github/workspace/$PATH /tmp/base
# git checkout $PREVIOUS_SHA
# cp /github/workspace/$PATH /tmp/revision

# oasdiff -format text -base /tmp/base -revision /tmp/revision
