on: [push]

jobs:
  oasdiff_job:
    runs-on: ubuntu-latest
    name: OpenAPI diff
    steps:
      - name: Compare specs
        id: compare
        uses: tufin/oasdiff-action@v1
        with:
          path: openapi-spec.yaml
